### ISSUE TITLE
[BackEnd] 김영광 작업지연 예상되어 공유드립니다.

### ISSUE THREAD

**Issue by 95Glory** [Manidle/Final-BackEnd#11]
금주 금요일 까지 맡은 엔티티 CRUD & JOIN이  제 feature/Refacor Branch에서의 Code Refactoring 으로 인해 지연될 것 같습니다.
토요일 까지 맡은 역할 해내겠습니다.

**Comment by soulchicken** [comment]
잘 마무리 되셨습니다
